import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createServer} from 'vite';import XLSX from 'xlsx';
const server=await createServer({server:{host:'127.0.0.1',port:5175,watch:{ignored:['**/chrome-profile/**','**/downloads/**']}}});await server.listen();
fs.mkdirSync('.tmp-check/downloads',{recursive:true});
const browser=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--no-sandbox','--disable-gpu','--remote-debugging-port=9225','--user-data-dir=C:/ABSEN MAGANG WEB/.tmp-check/chrome-profile','about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;
try {let pages;for(let i=0;i<50;i++){try{pages=await(await fetch('http://127.0.0.1:9225/json')).json();if(pages.some(p=>p.type==='page'))break}catch{}await new Promise(r=>setTimeout(r,100))}
socket=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[];socket.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}});const send=(method,params={})=>new Promise((resolve,reject)=>{const request=++id;pending.set(request,{resolve,reject});socket.send(JSON.stringify({id:request,method,params}))});const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;const waitFor=async expression=>{for(let i=0;i<100;i++){if(await evaluate(`Boolean(${expression})`))return;await new Promise(r=>setTimeout(r,100))}throw new Error('Timed out '+expression)};
await send('Runtime.enable');await send('Page.enable');await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:'C:/ABSEN MAGANG WEB/.tmp-check/downloads'});await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:5175/.tmp-check/index.html'});
await waitFor('document.querySelector("#reports .skeleton-loading")');assert.equal(await evaluate('[...document.querySelectorAll("#reports .export button")].every(b=>b.disabled)'),true);
assert.equal(await evaluate('!!document.querySelector(".attendance-trend .skeleton-chart")'),true);
await waitFor('document.querySelector("#reports .report-summary-desktop tbody tr")');
for(const status of ['Izin','Sakit','Alpa','Hadir','Terlambat','Selesai','Belum Absen']){await evaluate(`[...document.querySelectorAll('#switches button')].find(b=>b.textContent==='${status}').click()`);await new Promise(r=>setTimeout(r,30));assert.equal(await evaluate('document.querySelector("#dashboard .scan-cta").disabled'),['Izin','Sakit','Alpa','Selesai'].includes(status));if(['Izin','Sakit','Alpa'].includes(status)){assert.equal(await evaluate('document.querySelector("#dashboard").textContent.includes("Menunggu check-out")'),false);assert.equal(await evaluate('document.querySelector("#dashboard .status-card h3").textContent'),status)}}
await evaluate('document.querySelector("#reports .export button").click()');
for(let i=0;i<100&&!fs.readdirSync('.tmp-check/downloads').some(x=>x.endsWith('.xlsx'));i++)await new Promise(r=>setTimeout(r,100));
const excel=fs.readdirSync('.tmp-check/downloads').find(x=>x.endsWith('.xlsx'));if(!excel) console.log('Download diagnostics:', await evaluate('window.lastMessage'), fs.readdirSync('.tmp-check/downloads'), errors); assert.ok(excel);const book=XLSX.readFile('.tmp-check/downloads/'+excel);const summary=XLSX.utils.sheet_to_json(book.Sheets['Rekap per peserta']);assert.equal(summary[0].Izin,1);assert.equal(summary[0].Sakit,1);assert.equal(summary[0].Alpa,1);assert.equal(summary[0].Hadir,0);assert.ok(summary[0]['Tanpa catatan']>1);assert.ok(book.Sheets.Keterangan);
await waitFor('!document.querySelectorAll("#reports .export button")[1].disabled');await evaluate('document.querySelectorAll("#reports .export button")[1].click()');
for(let i=0;i<100&&!fs.readdirSync('.tmp-check/downloads').some(x=>x.endsWith('.pdf'));i++)await new Promise(r=>setTimeout(r,100));const pdf=fs.readdirSync('.tmp-check/downloads').find(x=>x.endsWith('.pdf'));assert.ok(pdf);const pdfText=fs.readFileSync('.tmp-check/downloads/'+pdf).toString('latin1');assert.ok(pdfText.startsWith('%PDF'));assert.ok(pdfText.includes('(Izin)'));assert.ok(pdfText.includes('(Tanpa catatan)'));assert.ok(pdfText.includes('(0)'));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate('document.documentElement.scrollWidth>innerWidth'),false);await evaluate('document.querySelector("#switches button").click()');fs.writeFileSync('.tmp-check/mobile.png',Buffer.from((await send('Page.captureScreenshot',{captureBeyondViewport:true})).data,'base64'));
await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await evaluate('getComputedStyle(document.querySelector(".skeleton-block")).animationName'),'none');
await evaluate('window.fail=true; document.querySelector("#reports .report-filter button").click()');await waitFor('document.querySelector("#reports [role=alert]")');assert.equal(await evaluate('[...document.querySelectorAll("#reports .export button")].every(b=>b.disabled)'),true);assert.equal(await evaluate('!!document.querySelector("#reports .report-stats")'),false);
await evaluate('window.fail=false; document.querySelector("#reports [role=alert] button").click()');await waitFor('document.querySelector("#reports .report-stats")');
assert.deepEqual(errors,[]);console.log('PASS: dashboard states/scan actions; skeletons; error/retry/export gating; actual Excel/PDF downloads and fields/zero values; mobile layout; reduced motion.');await send('Browser.close');
}finally{socket?.close();browser.kill();await server.close()}
