-- Jalankan SETELAH schema.sql lama. Tidak mengubah struktur lama.
create table if not exists public.system_settings (id smallint primary key default 1 check(id=1),work_start_time time not null default time '08:00',late_tolerance_minutes integer not null default 0 check(late_tolerance_minutes between 0 and 120),work_days smallint[] not null default array[1,2,3,4,5],qr_enabled boolean not null default true);
insert into public.system_settings(id) values(1) on conflict(id) do nothing;
alter table public.system_settings enable row level security;
drop policy if exists "settings admin" on public.system_settings;
create policy "settings admin" on public.system_settings for all using(public.is_admin()) with check(public.is_admin());
create table if not exists public.notifications(id bigint generated always as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
alter table public.notifications enable row level security;
drop policy if exists "notifications own" on public.notifications;
create policy "notifications own" on public.notifications for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create or replace function public.notify_attendance() returns trigger language plpgsql security definer set search_path=public as $$begin
 if tg_op='INSERT' then insert into notifications(user_id,title,message) values(new.user_id,'Absensi masuk berhasil','Check-in tercatat pukul '||to_char(new.check_in at time zone 'Asia/Jakarta','HH24:MI')||'. Status: '||new.status);
 elsif old.check_out is null and new.check_out is not null then insert into notifications(user_id,title,message) values(new.user_id,'Absensi pulang berhasil','Check-out tercatat pukul '||to_char(new.check_out at time zone 'Asia/Jakarta','HH24:MI')||'.'); end if;
 return new; end$$;
drop trigger if exists attendance_notification on public.attendance;
create trigger attendance_notification after insert or update of check_out on public.attendance for each row execute procedure public.notify_attendance();
-- Final replacement of scan function: only active interns can scan.
create or replace function public.scan_attendance(qr_token text,scan_latitude double precision,scan_longitude double precision) returns public.attendance language plpgsql security definer set search_path=public as $$declare a attendance;q qr_sessions;s time;t integer;d smallint[];e boolean;day_local date:=(now() at time zone 'Asia/Jakarta')::date;dist double precision;begin if not exists(select 1 from profiles where id=auth.uid() and role='intern' and is_active) then raise exception 'Hanya anak magang aktif yang dapat absensi';end if;select work_start_time,late_tolerance_minutes,work_days,qr_enabled into s,t,d,e from system_settings where id=1;if not coalesce(e,true) or not(extract(isodow from now() at time zone 'Asia/Jakarta')::smallint=any(coalesce(d,array[1,2,3,4,5]))) then raise exception 'Absensi tidak tersedia';end if;select * into q from qr_sessions where token=qr_token and is_active and expires_at>now();if q.id is null or q.latitude is null or scan_latitude is null or scan_longitude is null then raise exception 'QR atau lokasi tidak valid';end if;dist:=6371000*acos(least(1.0,greatest(-1.0,cos(radians(q.latitude))*cos(radians(scan_latitude))*cos(radians(scan_longitude)-radians(q.longitude))+sin(radians(q.latitude))*sin(radians(scan_latitude)))));if dist>q.radius_m then raise exception 'Di luar area absensi';end if;select * into a from attendance where user_id=auth.uid() and date=day_local for update;if a.id is null then insert into attendance(user_id,date,check_in,status) values(auth.uid(),day_local,now(),case when(now() at time zone 'Asia/Jakarta')::time>coalesce(s,time '08:00')+(coalesce(t,0)||' minutes')::interval then 'Terlambat' else 'Hadir'end) returning * into a;elsif a.check_out is null then update attendance set check_out=now() where id=a.id returning * into a;else raise exception 'Absensi hari ini sudah selesai';end if;return a;end$$;
grant execute on function public.scan_attendance(text,double precision,double precision) to authenticated;
